### ISSUE TITLE
Error importing Ninja Ripper 1.7.1 .rip files

### ISSUE THREAD

**Issue by Jobel91** [skyslide22/blender-addon-for-trackmania-and-maniaplanet#15]
Hello,

Thank you a lot for your work ! This addon is really helpful.
I having an issue trying to import Ninja Ripper 1.7.1 .rip files : 
![ErrorLog](https://user-images.githubusercontent.com/19471671/160301856-4f61ead8-d3f4-4386-8299-dcc7572710bb.jpg)

I don't change anything in the Ninja Ripper 1.7.1 settings.
I'm using Blender 3.0.1 and the 2.5.0 version of your addon.

Any idea where it might be coming from ?

Thank you in advance.

**Comment by croche63** [comment]
I also have this issue. It happens when trying to import a folder containing a few empty .rip files.
Here's a file that creates the crash :
[Mesh_0000.zip](https://github.com/skyslide22/blendermania-addon/files/13862991/Mesh_0000.zip)

Is it possible to add an option that automatically ignores files without any verts ?
